# Generated by Django 5.1.6 on 2025-02-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('resumen', models.CharField(max_length=2000)),
                ('foto', models.ImageField(upload_to='noticias/')),
                ('detalle', models.CharField(max_length=2000)),
                ('publicada', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
